<a href="https://colab.research.google.com/github/anamikaYadav7376/python-/blob/main/Day_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Pandas

used for data manipulation, cleaning, and analysis like excel sheet.

it handle large amount of data compare to excel.

In [94]:
import pandas as pd
# in compy we use cloud for datasheet

file_read = pd.read_csv('./student_data.csv', sep=',')

# print (file_read)

# print(file_read.head())   # this will print first 5 or 6 value

print(file_read.head(9))  # can put value (how many line we want to print)

   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8
4            5          52            8               6
5            7          40            9              10
6           10          40            4              11
7            3          86            7               3
8            7          72            8               5

   assignments_completed  previous_score  exam_score placement_status
0                     10              62      100.00           Placed
1                      8              56      100.00           Placed
2                     10              45      100.00           Placed
3                      4              55       90.17           Placed
4                      8              40       78.82           Placed
5                      0              60       72.33           Placed
6                      9              50       98.12           Placed
7                      7              85      100.00           Placed
8                     18              48       96.81           Placed

In [95]:
import pandas as pd

dct = {
    'name' : ["tom", 'Nick', 'krish',"jack"],
    'age' : [20,21,22,23],
    'roll' :[1,2,3,4]
}

df = pd.DataFrame(dct)

df1=pd.DataFrame(dct)

print(df)

# to print both we will use display
display(df)
display(df1)

    name  age  roll
0    tom   20     1
1   Nick   21     2
2  krish   22     3
3   jack   23     4

    name  age  roll
0    tom   20     1
1   Nick   21     2
2  krish   22     3
3   jack   23     4

    name  age  roll
0    tom   20     1
1   Nick   21     2
2  krish   22     3
3   jack   23     4

In [114]:
df = pd.read_csv('student_data.csv')

# print first 5 values
df.head(5)

# print last 3 values
# df.tail(3)

#
# df.shape

# metaData = data about data

# df.info()

#
# df.describe()

# q1 = 25% = first quatile
# q2 = 50% = second quatile
# q3 = 75% = third quatile

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [97]:
# will gives columns names

df.columns

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

In [98]:
# refers to the row labels

# gives howmany index of row , where it started , steps

df.index

RangeIndex(start=0, stop=10000, step=1)

In [99]:
# to acess data
df[['internet_usage','study_hours']]

# can be acess like this but not recomended
df.internet_usage

0        7
1        3
2        6
3        8
4        6
        ..
9995     7
9996     9
9997     5
9998     5
9999    11
Name: internet_usage, Length: 10000, dtype: int64

In [100]:
# to acess row / work on its own indexes

df.iloc[0:5]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [101]:
# all data frame / work on condition

df.loc[df['study_hours']==11]

# df.loc[df['study_hours']==11,['study_hours','sleep_hours']]

# to acess row from 4 to 7
# df.loc[df['study_hours']==11,['study_hours','sleep_hours']].iloc[3:7]


# df['assignments_completed']==8 # data frame

df.loc[df['assignments_completed']==8,["assignments_completed"]].iloc[1:2]

   assignments_completed
4                      8

In [102]:
# filteration of data based on a condition

df[df["assignments_completed"]>8]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
6,10,40,4,11,9,50,98.12,Placed
8,7,72,8,5,18,48,96.81,Placed
9,11,77,4,9,15,69,100.00,Placed
...,...,...,...,...,...,...,...,...
9992,5,100,9,2,9,62,100.00,Placed
9993,10,86,9,9,15,63,100.00,Placed
9994,4,53,7,8,10,71,85.02,Placed
9997,10,44,8,5,10,37,95.94,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [103]:
# to add new data frame

df["age"]=20

df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [104]:
# rename a columns
# it will return new data so we have to store it somewhere

# df = df.rename(columns={'assignments_completed' : "assign"})

# df


# to replace inplace (do not want new variable)

df.rename(columns={'assignments_completed' : "assign"},inplace=True)

df

,study_hours,attendance,sleep_hours,internet_usage,assign,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [105]:
# Remove rows or columns

# Using the columns parameter (Recommended)
# df_new = df.drop(columns='assignments_completed')
# df_new

# Using axis=1
# df_new = df.drop('assignments_completed', axis=1)
# df_new

# remove multiple columns
# df_new = df.drop(columns=['assignments_completed', 'study_hours'])
# df_new

# Using the index parameter
# df_new = df.drop(index=1)
# df_new

# Using default axis
# df_new = df.drop(0)
# df_new

# remove multiple rows
df_new = df.drop(index=[0, 1, 2])
df_new

# inplace
df.drop(columns='age', inplace=True)

#  Prevents the code from crashing if the specified label does not exist.
df.drop(columns='non_existent_column', errors='ignore')

,study_hours,attendance,sleep_hours,internet_usage,assign,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [106]:
# remove missing values
# df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False, ignore_index=False)

import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', np.nan],
    'Age': [25, np.nan, np.nan, np.nan],
    'City': ['New York', 'London', np.nan, np.nan]
}

# df = pd.DataFrame(data)

df_clean = df.dropna()
df_clean

,study_hours,attendance,sleep_hours,internet_usage,assign,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [115]:
import pandas as pd
df = pd.read_csv('student_data.csv')
df['assignments_completed'].unique()

array([10,  8,  4,  0,  9,  7, 18, 15, 12, 17,  3, 13,  6, 11, 14, 19, 16,
        5, 20,  1,  2])

In [109]:
# how to use lamda function in sorting = home Work

# check for missing values
# df.isnull()

# # check for non-missing values
# df.notnull()

# # Replace missing values
# df.fillna()

# # Find unique values  # For series only
# df.unique()

# # aggregate nultiple statics
# df.agg()